distributable:
  url: https://github.com/stedolan/jq/releases/download/jq-{{version.raw}}/jq-{{version.raw}}.tar.gz
  strip-components: 1

versions:
  github: stedolan/jq
  strip: /jq /

dependencies:
  github.com/kkos/oniguruma: 6

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    linux:
      llvm.org: '>=12<15'
    git-scm.org: 2
  script: |
    if test '{{hw.platform}}' = 'darwin'; then
      git apply props/darwin.diff
      git apply props/lgamma_r.diff
    fi
    ./configure --disable-maintainer-mode --prefix={{prefix}}
    make install

test:
  script: test $(jq .devs[1].github < test.json) = '"jhheider"'

provides:
  - bin/jq