distributable:
  url: https://registry.npmjs.org/pnpm/-/pnpm-{{version}}.tgz
  strip-components: 1

versions:
  github: pnpm/pnpm

provides:
  - bin/pnpm

dependencies:
  nodejs.org: '>=16'

build:
  script: |
    cp bin/pnpm.cjs bin/pnpm
    cp -r . {{prefix}}

test:
  script: |
    pnpm doctor
