distributable:
  url: https://github.com/lz4/lz4/archive/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: lz4/lz4
  strip: /^LZ4 /

provides:
  - bin/lz4

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script:
    make --jobs {{hw.concurrency}} install PREFIX="{{prefix}}"

test:
  fixture:
    testing compression and decompression
  script: |
    cat $FIXTURE | lz4 | lz4 -d > out
    test "$(cat $FIXTURE)" = "$(cat out)"
