distributable:
  url: https://github.com/tsl0922/ttyd/archive/{{version}}.tar.gz
  strip-components: 1

dependencies:
  libuv.org: 1
  github.com/json-c/json-c: ^0.16
  libwebsockets.org: 4
  zlib.net: 1

versions:
  github: tsl0922/ttyd

build:
  dependencies:
    cmake.org: 3
    tea.xyz/gx/make: '*'
    tea.xyz/gx/cc: 'c99'
  working-directory: build
  script: |
    cmake .. -DCMAKE_INSTALL_PREFIX="{{prefix}}"
    make --jobs {{hw.concurrency}}
    make install

#TODO test functionality
test:
  ttyd --help

provides:
  - bin/ttyd
