distributable: ~

# FIXME we want the c version eg. c99 
# or should that be some kind of option? so you specify you want a cc that support c99
versions:
  - 0.1.2

dependencies:
  linux:
    llvm.org: '<15'   # Right now, at least 8 packages don't build with llvm^15 in the environment.
                      # There shouldn't be any particular harm with limiting this for now. But, it
                      # should definitely be FIXME.
  darwin:
    apple.com/xcode/clt: '*'

build:
  working-directory:
    ${{prefix}}/bin
  script: |
    if test {{ hw.platform }} = darwin; then
      cp "$SRCROOT"/props/ld .
      cp "$SRCROOT"/props/cc.rb cc
    else
      ln -s "$LLVM"/clang cc
      ln -s "$LLVM"/lld ld
      for x in ar as strip objcopy nm objdump ranlib readelf strings; do
        ln -sf "$LLVM"/llvm-$x $x
      done
    fi

    for x in clang gcc clang++ c++ g++; do
      ln -s cc $x
    done
    for x in lld-link lld ld64.lld; do
      ln -s ld $x
    done

    # dunno why we gotta do this, but we do
    chmod 777 *
  env:
    LLVM: ../../../../../llvm.org/v*/bin

test: |
  cc --version
  ld --help

provides:
  - bin/c++
  - bin/cc
  - bin/clang
  - bin/clang++
  - bin/g++
  - bin/gcc
  - bin/ld
  - bin/ld64.lld
  - bin/lld
  - bin/lld-link
