distributable:
  url: https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-{{version.raw}}.tar.bz2
  strip-components: 1

versions:
  - 1.45

provides:
  - bin/gpg-error
  - bin/gpg-error-config
  - bin/gpgrt-config
  - bin/yat2m

build:
  script: |
    ./configure --prefix={{prefix}}
    make
    make check
    make install
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'

test:
  script: test "$(gpg-error 56)" = "$OUTPUT"
  env:
    OUTPUT: "56 = (0, 56) = (GPG_ERR_SOURCE_UNKNOWN, GPG_ERR_BAD_CERT_CHAIN) = (Unspecified source, Bad certificate chain)"
