distributable:
  url: https://cache.ruby-lang.org/pub/ruby/{{version.marketing}}/ruby-{{version}}.tar.xz
  strip-components: 1

versions:
  github: ruby/ruby/tags

dependencies:
  openssl.org: ^1.1
  pyyaml.org: ^0.2
  zlib.net: 1

build:
  dependencies:
    freedesktop.org/pkg-config: ^0.29
    gnu.org/gettext: ^0.21
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    ./configure --prefix="{{prefix}}" --enable-load-relative
    make --jobs {{hw.concurrency}} install

    cd "{{prefix}}"/bin

    # we provide these as `rubygems.org`
    rm bundle bundler gem rake rbs rdbg typeprof

    for shim in $shims; do
      sed -i.bak -e 's_#!{{prefix}}/bin/ruby_#!/usr/bin/env ruby_' $shim
      rm $shim.bak
    done
  env:
    shims:
      - erb
      - irb
      - racc
      - rdoc
      - ri

test: |
  ruby -e 'puts "Hello World!"'

provides:
  - bin/erb
  - bin/irb
  - bin/racc
  - bin/rdoc
  - bin/ri
  - bin/ruby

interprets:
  extensions: rb
  args: ruby

companions:
  rubygems.org: '*'
