distributable:
  url: https://ftp.gnu.org/gnu/gettext/gettext-{{version.raw}}.tar.gz
  strip-components: 1

dependencies:
  gnome.org/libxml2: 2
  #TODO ncurses

versions:
  github: autotools-mirror/gettext/tags
  strip: /v/

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    ./configure \
      --prefix={{ prefix }} \
      --disable-debug \
      --with-included-debug \
      --with-included-libcroco \
      --with-included-libunistring \
      --without-included-libxml \
      --disable-java \
      --disable-csharp
    make --jobs {{ hw.concurrency }}
    make install

test: gettext test

provides:
  - bin/autopoint
  - bin/envsubst
  - bin/gettext
  - bin/gettext.sh
  - bin/gettextize
  - bin/msgattrib
  - bin/msgcat
  - bin/msgcmp
  - bin/msgcomm
  - bin/msgconv
  - bin/msgen
  - bin/msgexec
  - bin/msgfilter
  - bin/msgfmt
  - bin/msggrep
  - bin/msginit
  - bin/msgmerge
  - bin/msgunfmt
  - bin/msguniq
  - bin/ngettext
  - bin/recode-sr-latin
  - bin/xgettext
