distributable:
  #FIXME
  url: https://hackage.haskell.org/package/pandoc-crossref-0.3.13.0/pandoc-crossref-0.3.13.0.tar.gz
  strip-components: 1

versions:
  - 0.3.13

dependencies:
  pandoc.org: ^2.18
  zlib.net: 1
  gnu.org/gmp: 6

build:
  dependencies:
    tea.xyz/gx/cc: c99
    haskell.org: ^9
    haskell.org/cabal: ^3
  script: |-
    cabal update
    cabal install --install-method=copy --installdir={{prefix}}/bin

test: true  #FIXME

provides:
  - bin/pandoc-crossref