distributable:
  url: http://ftp.midnight-commander.org/mc-{{ version }}.tar.xz
  strip-components: 1

versions:
  github: MidnightCommander/mc/tags

provides:
  - bin/mc
  - bin/mcdiff
  - bin/mcedit
  - bin/mcview

dependencies:
  invisible-island.net/ncurses: '*'
  gnome.org/glib: '>=2.30'
  gnu.org/gettext: '>=0.18.2'

runtime:
  env:
    #FIXME we prefer to fix this in the binary
    MC_DATADIR: '{{prefix}}/etc/mc/'

build:
  dependencies:
    tea.xyz/gx/cc: '*'
    tea.xyz/gx/make: '*'
    gnu.org/autoconf: '>=2.64'
    gnu.org/automake: '>=1.12'
    gnu.org/libtool: '*'
    freedesktop.org/pkg-config: '^0.29'
  script: |
    ./configure $ARGS
    make -j {{hw.concurrency}}
    make install

    cd "{{prefix}}"
    fix-shebangs.ts libexec/mc/extfs.d/*

    for x in $(find libexec/mc -name \*sh -type f -depth 1) libexec/mc/ext.d/misc.sh; do
      sed -i.bak 's|{{tea.prefix}}|$TEA_PREFIX|g' $x
      rm $x.bak
    done

    sed -i.bak 's|{{tea.prefix}}|%p/../|g' etc/mc/mc.ext
    rm etc/mc/mc.ext.bak

  env:
    ARGS:
      - --prefix={{prefix}}
      - --with-screen=ncurses
    # Needed for the compiler to `#include <term.h>`
    CPATH: $CPATH:{{deps.invisible-island.net/ncurses.prefix}}/include/ncursesw

# FIXME: hard to test interactive tools
test:
  test "$(mc --datadir | cut -d ' ' -f1 | cut -d':' -f1)" = "{{prefix}}/etc/mc/"
# ^^ tests relocatability
