distributable:
  url: https://ftp.gnu.org/gnu/make/make-{{ version.raw }}.tar.gz
  strip-components: 1

versions:
  # github: mirror/make/tags -- these versions don't match the source versions...
  - 4.3

provides:
  - bin/make

build:
  dependencies:
    gnu.org/m4: 1
    tea.xyz/gx/make: '*'  #FIXME bootstrapping system
    tea.xyz/gx/cc: c99
  script: |
    ./configure --prefix={{ prefix }} --disable-dependency-tracking
    make --jobs {{ hw.concurrency }} install

test:
  #TODO build self
  script: |
    make --file=$FIXTURE
    test "$(cat foo)" = bar
    make --question --file=$FIXTURE
  fixture:
    "foo:\n\techo bar > $@"
  env:
    MAKEFLAGS: --file=$FIXTURE
