distributable:
  url: https://github.com/mikefarah/yq/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

versions:
  github: mikefarah/yq/releases/tags

build:
  script: |
    go build -v -ldflags="$LDFLAGS"
    ./scripts/generate-man-page-md.sh
    ./scripts/generate-man-page.sh
    mkdir -p "{{ prefix }}"/bin
    mv yq "{{ prefix }}"/bin
    mkdir -p "{{ prefix }}"/share/man/man1
    mv yq.1 "{{ prefix }}"/share/man/man1
  dependencies:
    go.dev: ^1.18
    pandoc.org: '*'
  env:
    LDFLAGS:
      - -s -w
    linux:
      LDFLAGS:
      - -buildmode=pie

test:
  yq --version

provides:
  - bin/yq