distributable:
  url: https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-{{version}}.tar.bz2
  strip-components: 1

versions:
  - 1.10.1

provides:
  - bin/dumpsexp
  - bin/hmac256
  - bin/libgcrypt-config
  - bin/mpicalc

build:
  script: |
    ./configure --prefix={{prefix}}
    make
    make check
    make install
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    gnupg.org/libgpg-error: 1

test:
  script: |
    OUT=$(echo foo | hmac256 -)
    test "$OUT" = "9619c032ccc62b07274634a032c322580848455327d4a9aa3d323702673cf2a2"
